apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      version: v4.4
  template:
    metadata:
      labels:
        app: frontend
        version: v4.4
    spec:
      containers:
      - name: frontend
        image: muteeat/shopeasy-frontend:52dbc59a1c7375885d46374fdb4c4480b5a5ac79
        ports:
        - containerPort: 8080
